const mealsByName = [
  {
    idMeal: '52771',
    strMeal: 'Spicy Arrabiata Penne',
    strDrinkAlternate: null,
    strCategory: 'Vegetarian',
    strArea: 'Italian',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
    strTags: 'Pasta,Curry',
    strYoutube: 'https://www.youtube.com/watch?v=1IszT_guI08',
    strIngredient1: 'penne rigate',
    strIngredient2: 'olive oil',
    strIngredient3: 'garlic',
    strIngredient4: 'chopped tomatoes',
    strIngredient5: 'red chile flakes',
    strIngredient6: 'italian seasoning',
    strIngredient7: 'basil',
    strIngredient8: 'Parmigiano-Reggiano',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: '1 pound',
    strMeasure2: '1/4 cup',
    strMeasure3: '3 cloves',
    strMeasure4: '1 tin ',
    strMeasure5: '1/2 teaspoon',
    strMeasure6: '1/2 teaspoon',
    strMeasure7: '6 leaves',
    strMeasure8: 'spinkling',
    strMeasure9: '',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: null,
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
];

const mealsByIngredients = [
  {
    strMeal: 'Chick-Fil-A Sandwich',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg',
    idMeal: '53016',
  },
  {
    strMeal: 'Chicken Couscous',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/qxytrx1511304021.jpg',
    idMeal: '52850',
  },
  {
    strMeal: 'Chicken Fajita Mac and Cheese',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg',
    idMeal: '52818',
  },
  {
    strMeal: 'Chicken Ham and Leek Pie',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/xrrtss1511555269.jpg',
    idMeal: '52875',
  },
  {
    strMeal: 'Chicken Quinoa Greek Salad',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/k29viq1585565980.jpg',
    idMeal: '53011',
  },
  {
    strMeal: 'General Tso\'s Chicken',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1529444113.jpg',
    idMeal: '52951',
  },
  {
    strMeal: 'Honey Balsamic Chicken with Crispy Broccoli & Potatoes',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/kvbotn1581012881.jpg',
    idMeal: '52993',
  },
  {
    strMeal: 'Katsu Chicken curry',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg',
    idMeal: '52820',
  },
  {
    strMeal: 'Rappie Pie',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/ruwpww1511817242.jpg',
    idMeal: '52933',
  },
];

const mealsByFirstLetter = [
  {
    idMeal: '52768',
    strMeal: 'Apple Frangipan Tart',
    strDrinkAlternate: null,
    strCategory: 'Dessert',
    strArea: 'British',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg',
    strTags: 'Tart,Baking,Fruity',
    strYoutube: 'https://www.youtube.com/watch?v=rp8Slv4INLk',
    strIngredient1: 'digestive biscuits',
    strIngredient2: 'butter',
    strIngredient3: 'Bramley apples',
    strIngredient4: 'butter, softened',
    strIngredient5: 'caster sugar',
    strIngredient6: 'free-range eggs, beaten',
    strIngredient7: 'ground almonds',
    strIngredient8: 'almond extract',
    strIngredient9: 'flaked almonds',
    strMeasure1: '175g/6oz',
    strMeasure2: '75g/3oz',
    strMeasure3: '200g/7oz',
    strMeasure4: '75g/3oz',
    strMeasure5: '75g/3oz',
    strMeasure6: '2',
    strMeasure7: '75g/3oz',
    strMeasure8: '1 tsp',
    strMeasure9: '50g/1¾oz',
  },
  {
    idMeal: '52893',
    strMeal: 'Apple & Blackberry Crumble',
    strDrinkAlternate: null,
    strCategory: 'Dessert',
    strArea: 'British',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg',
    strTags: 'Pudding',
    strYoutube: 'https://www.youtube.com/watch?v=4vhcOwVBDO4',
    strIngredient1: 'Plain Flour',
    strIngredient2: 'Caster Sugar',
    strIngredient3: 'Butter',
    strIngredient4: 'Braeburn Apples',
    strIngredient5: 'Butter',
    strIngredient6: 'Demerara Sugar',
    strIngredient7: 'Blackberrys',
    strIngredient8: 'Cinnamon',
    strIngredient9: 'Ice Cream',
    strMeasure1: '120g',
    strMeasure2: '60g',
    strMeasure3: '60g',
    strMeasure4: '300g',
    strMeasure5: '30g',
    strMeasure6: '30g',
    strMeasure7: '120g',
    strMeasure8: '¼ teaspoon',
    strMeasure9: 'to serve',
    strSource:
      'https://www.bbcgoodfood.com/recipes/778642/apple-and-blackberry-crumble',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: '53049',
    strMeal: 'Apam balik',
    strDrinkAlternate: null,
    strCategory: 'Dessert',
    strArea: 'Malaysian',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=6R8ffRRJcrg',
    strIngredient1: 'Milk',
    strIngredient2: 'Oil',
    strIngredient3: 'Eggs',
    strIngredient4: 'Flour',
    strIngredient5: 'Baking Powder',
    strIngredient6: 'Salt',
    strIngredient7: 'Unsalted Butter',
    strIngredient8: 'Sugar',
    strIngredient9: 'Peanut Butter',
    strMeasure1: '200ml',
    strMeasure2: '60ml',
    strMeasure3: '2',
    strMeasure4: '1600g',
    strMeasure5: '3 tsp',
    strMeasure6: '1/2 tsp',
    strMeasure7: '25g',
    strMeasure8: '45g',
    strMeasure9: '3 tbs',
    strSource: 'https://www.nyonyacooking.com/recipes/apam-balik~SJ5WuvsDf9WQ',
  },
  {
    idMeal: '53050',
    strMeal: 'Ayam Percik',
    strCategory: 'Chicken',
    strArea: 'Malaysian',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/020z181619788503.jpg',
    strYoutube: 'https://www.youtube.com/watch?v=9ytR28QK6I8',
    strIngredient1: 'Chicken Thighs',
    strIngredient2: 'Challots',
    strIngredient3: 'Ginger',
    strIngredient4: 'Garlic Clove',
    strIngredient5: 'Cayenne Pepper',
    strIngredient6: 'Turmeric',
    strIngredient7: 'Cumin',
    strIngredient8: 'Coriander',
    strIngredient9: 'Fennel',
    strIngredient10: 'Tamarind Paste',
    strIngredient11: 'Coconut Milk',
    strIngredient12: 'Sugar',
    strIngredient13: 'Water',
    strMeasure1: '6',
    strMeasure2: '16',
    strMeasure3: '1 1/2 ',
    strMeasure4: '6',
    strMeasure5: '8',
    strMeasure6: '2 tbs',
    strMeasure7: '1 1/2 ',
    strMeasure8: '1 1/2 ',
    strMeasure9: '1 1/2 ',
    strMeasure10: '2 tbs',
    strMeasure11: '1 can ',
    strMeasure12: '1 tsp ',
    strMeasure13: '1 cup ',
    strSource: 'http://www.curiousnut.com/roasted-spiced-chicken-ayam-percik/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
];

export { mealsByName, mealsByFirstLetter, mealsByIngredients };
